//
// Created by gc on 10/17/20.
//


#include "gtest/gtest.h"
#include "fstream"
#include "../../src/libcalculators/REVCCalculator.h"
#include "../../src/validators/REVCValidator.h"

#define infile "../../input_txt/rosalind_revc.txt"
#define output "GCTAGAACAACGTGAATGTCCACCGTCAACACTCAGGTGCTTTTTAAGGAAATGATTGTACCTATTAGCCCCTTTCAATAACTGCCCCAGCAATCTCTGGAAACTGAGACTAAGTCTCTGTGCCCACTCATGGGGTCTCTGTCTTGGAAATTGCCACAAACCAGTCACTAGTAAGGCTGCTGTCGTCTATGACCGAAATGCCAAGCCAATGGGTCTTGTACGTGATATATACCCTCTGACTATTCTACTCGATTAGGGATGACATTCGTAGCAGTACCTAGTCTCCACTGGTACCTAGTGGGCCAACGCGTTTCACGCCTTGAGTACTGTCAATGTTGCGATCTGATAAAAGGGCGACACCCAACCTCAATAAGTTAGGCGTGTGATGAAGTTGGGACGTACTCGACATGTAATTCTATAAATGTGGTTCCGGCGCCCTAGTGGTTCTGACATATCGCGAGTAGGGCGGCACGCCAAGGCATATTTACCAAAGGAATTCTCTTGTGAGTGGTTCATGGGGGTCTAGCAGTCATAGGCAATTCAATAACGTGTAAGGTTTCACCGGGTGAGCTGAGCTGAGTACAAAGACTTAATCCGGCATCCTCCCGTTCGTCTTTCTTTAGTGCCATATCAGCACTAAAGTCACTCACGGACTTTATCCGTACTGATTGAGCTATCAAGATAAGTACAATAGCAAGCGAGCCAGTTGTCCTTGTAGTGAGCGACGGTGAAGCATTCTGTGTCGCGGTGGGTAAGGCGGAACTCCAATCCCACGGAAACATATATGCGTACAACGACGGCTTGACCACTGGGCTCCAGTCCAAGCCGCCCCTCCTCAAAGGGGACCAGATGCAACTAAACGCTTCACCCGACTATTAGCTGACGGAACA"


TEST(REVC_Validator, validate) {
    std::ifstream fin;
    std::string rosalind_dna_string;
    fin.open(infile);
    getline(fin, rosalind_dna_string);

    ASSERT_TRUE(REVCValidator::validate(REVCCalculator::calculate(rosalind_dna_string), output));

}

TEST(REVC_Validator, validate_with_sample_input) {
    std::string input = "AAAACCCGGT";
    std::string out = "ACCGGGTTTT";

    ASSERT_TRUE(REVCValidator::validate(REVCCalculator::calculate(input), out));

}

