#include <iostream>
#include "libcalculators/DNACalculator.h"

int main() {
    std::string s = "GGCAGACTTGGACTTCATACAGGGGTGCCATGACGATATCTTGGCCAACGTGAGTTATTTTGGCCGCCCCCTGAATTGCGACTTGTAATGCCTGACTAACACTACTGCATCTTTTACGAATAGATGACCTCACTAACTGCGGAAATAATCCACCTTTTATGGAACGATTCGGCCATCCAATGCCTGCTATGAGTTCTTGCTGAGACAGACTGAATGTCCTCACTTAGTCAGGCCTCCTGGCGGGAGTGGTCCAAGCTACCGTCGACCCAAGCCGGCCAGTAATTGGGGAAACCTAGTGTATGTCAGGTCTATCGTAGAACTGCATGGCGCAAGTAAAGAAGGTCCCTCGCGGAGCAGGGTGCCGAAATCAGAACGACGGAATCCAGTAGCAATACGAACGCACAGCTTCTATCAGCAGTCTAATCCAGACTTATCTCGGGCTCACCAAGGCGCACCTTCCCTGTACATTCTAACGGAATGAATCTGTGCTATAGGTAGCCAGTAATAGGTGCAGCTGGCCAGCGCGGAGCGGTTCGTTTGGCTCTTGGGGGGCTAAATTATTCTCCCCTATGCCGTATGAAAATTTGATAACATGGGCCTTTGACTAACAGTAGGACATGTATCAACAAACATCATCTTCATACTGCTGGGCCCCCGGTATTCCGTAATGGGGAGGATGAGCTGCAGCGGCTAGGTAAAGGCCGCGGTCGCTTTAGGAGCGGTTTAAAGATGGGCACTGTCTGAAATTGATCTTGTCTGGGTTTCTATGCAGCGGAGTAAACGCACGCCATAGCGAATGAGATGCCATGCGGTCAATTCGTCCGTCTGAAACTCAGCAAACATTACATCGTGATTACTGC";
    std::cout << "A: " << DNACalculator::count('A', s) << std::endl;
    std::cout << "C: " << DNACalculator::count('C', s) << std::endl;
    std::cout << "G: " << DNACalculator::count('G', s) << std::endl;
    std::cout << "T: " << DNACalculator::count('T', s) << std::endl;


    return 0;
}
